packages:
  - "app"
  - "packages/*"
  - "packages/slint-gallery/node"
  - "packages/base-ui-gallery/node"

catalog:
  "@types/node": "25.5.0"
  oxfmt: "0.50.0"
  oxlint: "1.65.0"
  typescript: "6.0.3"
  slint-ui: "1.17.0"
  cross-env: "10.1.0"

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  slint-ui: true

savePrefix: ""
