packages:
  - "app"
  - "packages/*"
  - "packages/slint-gallery/node"

catalog:
  "@types/node": "25.5.0"
  oxfmt: "0.46.0"
  oxlint: "1.61.0"
  typescript: "6.0.3"
  slint-ui: "1.17.0-nightly.2026050221"
  cross-env: "10.1.0"
