export struct ProjectRow {
    title: string,
    number: int,
    url: string,
}

export struct ReviewRequestRow {
    title: string,
    url: string,
    repo_label: string,
}

export enum Authed {
    loggedOut,
    noGhCliInstalled,
    loggedIn,
    authorizing,
}

export enum View {
    none,
    dashboard,
    settings
}

export global AppState {
    in-out property <Authed> auth: loggedOut;
    in-out property <string> user_login: "";
    in-out property <string> user_name: "";
    in-out property <string> user_profile_url: "";
    in-out property <string> user_status_message: "";
    in-out property <string> user_status_emoji: "";
    in-out property <image> avatar;

    in-out property <bool> review-requests-data-ready: false;
    in-out property <int> review-requests-total: 0;
    in-out property <string> review-requests-load-status: "";
    in property <[ReviewRequestRow]> review-requests-model;

    in-out property <View> view: none;
    callback set-view(View);
    callback dashboard-init;
    callback settings-init;

    set-view(view) => {
        if view == self.view {
            self.view = View.none;
        } else {
            self.view = view;
        }
    }

    in-out property <string> projects-search: "";
    in-out property <string> projects-load-status: "";
    in property <[ProjectRow]> projects-filtered-model;
    callback project-search-changed(string);
    callback sign-out;
    callback open-project-url(string);
}
