export struct ProjectRow {
    title: string,
    number: int,
    url: string,
}

export enum Authed {
    loggedOut,
    noGhCliInstalled,
    loggedIn,
    authorizing,
}

export global AppState {
    in-out property <Authed> auth: loggedOut;
    in-out property <string> user_login: "";
    in-out property <string> user_name: "";
    in-out property <string> user_profile_url: "";
    in-out property <string> user_status_message: "";
    in-out property <string> user_status_emoji: "";
    in-out property <image> avatar;
    in-out property <bool> show-settings: false;

    in-out property <string> projects-search: "";
    in-out property <string> projects-load-status: "";
    in property <[ProjectRow]> projects-filtered-model;
    callback project-search-changed(string);
    callback sign-out;
}
