import { ListView, VerticalBox } from "std-widgets.slint";
import { AppState } from "app-state.slint";

export component Dashboard {
    width: 100%;
    height: 100%;

    init => {
        AppState.dashboard-init();
    }

    Rectangle {
        width: 100%;
        height: 100%;
        background: #020408;

        VerticalBox {
            padding: 16px;
            spacing: 12px;
            width: 100%;
            height: 100%;

            Text {
                text: "Review requests";
                font-size: 14px;
                font-weight: 600;
                color: #c9d1d9;
            }

            Rectangle {
                height: 47px;
                background: #26211A;
                border-radius: 6px;
                border-width: 1px;
                border-color: #5F4921;

                visible: AppState.review-requests-total > 0;

                HorizontalLayout {
                    x: 0;
                    padding: 14px;
                    spacing: 14px;
                    width: self.preferred-width;
                    Image {
                        source: @image-url("../assets/16px/alert.svg");
                        colorize: #CA9C3E;
                    }

                    Text {
                        text: AppState.review-requests-total + " pull requests are waiting on your review.";
                        font-size: 14px;
                        font-weight: 400;
                        color: #f0f6fc;
                        vertical-alignment: center;
                    }
                }
            }

            if AppState.review-requests-load-status != "": Text {
                text: AppState.review-requests-load-status;
                color: #8b949e;
                wrap: word-wrap;
            }

            ListView {
                width: 100%;
                for row[index] in AppState.review-requests-model: Rectangle {
                    height: 56px;
                    background: mod(index, 2) == 0 ? #0d1116 : #161b22;

                    TouchArea {
                        clicked => {
                            AppState.open_project_url(row.url);
                        }

                        VerticalBox {
                            padding: 8px;
                            spacing: 4px;
                            Text {
                                text: row.title;
                                color: #f0f6fc;
                                overflow: elide;
                            }

                            Text {
                                text: row.repo_label;
                                font-size: 12px;
                                color: #8b949e;
                            }
                        }
                    }
                }
            }
        }
    }
}
