import { AppState } from "app-state.slint";

global HeaderStyle {
    out property <length> border-radius: 12px;
    out property <length> menu-width: 256px;

    out property <color> header-background: #020408;
    out property <color> menu-item-text-color: #f0f6fc;
}

global HeaderState {
    in-out property <bool> menu-visible: false;
}

component Avatar {

    in-out property source <=> avatar.source;

    width: 34px;
    height: self.width;

    Rectangle {
        width: parent.width - 2px;
        height: self.width;
        border-radius: self.width / 2;
        clip: true;
        avatar := Image {
            width: parent.width;
            height: self.width;
        }
    }

    Rectangle {
        border-width: 1px;
        border-color: #28292d;
        border-radius: self.width / 2;
    }

    @children
}

component MenuItem {

    in-out property icon-source <=> icon.source;
    in-out property label-text <=> label.text;
    callback clicked;

    width: HeaderStyle.menu-width;
    height: content.preferred-height;

    ta := TouchArea {
        clicked => {
            HeaderState.menu-visible = false;
            root.clicked();
        }
    }

    content := HorizontalLayout {
        x: 0;
        width: self.preferred-width;
        height: 16px;
        padding-left: 16px;
        padding-right: 16px;
        Rectangle {
            width: 20px;
            height: 16px;
            Rectangle {
                x: 0;
                width: 16px;
                height: self.width;
                icon := Image {
                    width: 100%;
                    height: 100%;
                    colorize: HeaderStyle.menu-item-text-color;
                }
            }
        }

        label := Text {
            y: -self.font-metrics.descent - 1px;
            font-size: 14px;
            font-weight: 400;
            color: HeaderStyle.menu-item-text-color;
        }
    }
}

component MenuSeparator inherits VerticalLayout {
    height: self.preferred-height;
    width: 100%;
    padding-left: 8px;
    padding-right: 8px;
    Rectangle {
        height: 8px;
    }

    Rectangle {
        height: 1px;
        background: #2b3139;
    }

    Rectangle {
        height: 8px;
    }
}

component Menu {

    in-out property <image> avatar-source <=> avatar.source;

    width: HeaderStyle.menu-width;
    height: content.preferred-height;

    // Block clicks
    TouchArea { }

    Rectangle {
        border-radius: HeaderStyle.border-radius;
        drop-shadow-offset-y: 6px;
        drop-shadow-blur: 18px;
        drop-shadow-color: #01040966;
    }

    Rectangle {
        border-radius: HeaderStyle.border-radius;
        drop-shadow-offset-y: 6px;
        drop-shadow-blur: 12px;
        drop-shadow-color: #01040966;
    }

    Rectangle {
        border-radius: HeaderStyle.border-radius;
        border-width: 1px;
        border-color: #3e444d;
        background: HeaderStyle.header-background;
    }

    content := VerticalLayout {
        y: 0;
        height: self.preferred-height;
        Rectangle {
            height: 16px;
        }

        header-content := Rectangle {
            x: 16px;
            width: parent.width - (2 * self.x);
            height: 100px - 16px;

            VerticalLayout {
                spacing: 8px;
                width: parent.width;
                HorizontalLayout {
                    spacing: 8px;
                    width: self.preferred-width;

                    avatar := Avatar { }

                    VerticalLayout {
                        y: 3px;
                        height: self.preferred-height;
                        spacing: 4px;
                        Text {
                            width: 120px;
                            text: AppState.user_login;
                            visible: AppState.user_login != "";
                            font-size: 14px;
                            font-weight: 550;
                            color: HeaderStyle.menu-item-text-color;
                            overflow: elide;
                        }

                        Text {
                            width: 120px;
                            text: AppState.user_name;
                            visible: AppState.user_name != "";
                            font-size: 14px;
                            color: #9198a1;
                            font-weight: 400;
                            overflow: elide;
                            letter-spacing: 0.15px;
                        }
                    }
                }
            }

            HorizontalLayout {
                x: 0px;
                y: parent.height - self.height - 14px;
                spacing: 8px;
                width: self.preferred-width;
                height: self.preferred-height;

                Text {
                    text: AppState.user_status_emoji;
                    visible: AppState.user_status_emoji != "";
                    font-size: 14px;
                }

                Text {
                    text: AppState.user_status_message;
                    visible: AppState.user_status_message != "";
                    font-size: 14px;
                    color: HeaderStyle.menu-item-text-color;
                    font-weight: 400;
                }
            }
        }

        MenuSeparator { }

        MenuItem {
            icon-source: @image-url("../assets/16px/sign-out.svg");
            label-text: "Sign out";
            clicked => {
                AppState.sign-out();
            }
        }

        Rectangle {
            height: 16px;
        }
    }
}

export component Header {
    width: 100%;
    height: 100%;

    out property <length> header-height: 64px;

    Rectangle {
        y: 0;
        width: 100%;
        height: root.header-height;
        Rectangle {
            background: HeaderStyle.header-background;
        }

        Rectangle {
            y: parent.height - self.height;
            width: 100%;
            height: 1px;
            background: #3e444d;
        }

        avatar-container := Avatar {
            x: parent.width - self.width - self.y;
            y: (parent.height - self.height) / 2;
            source: AppState.avatar;
            TouchArea {
                clicked => {
                    HeaderState.menu-visible = true;
                }
            }
        }

        TouchArea {
            y: 0;
            width: root.width;
            height: root.height;
            visible: HeaderState.menu-visible;
            clicked => {
                HeaderState.menu-visible = false;
            }
        }

        menu := Menu {
            x: parent.width - self.width - 14px;
            y: avatar-container.y + avatar-container.height + 2px;
            avatar-source: AppState.avatar;
            visible: HeaderState.menu-visible;
        }
    }
}
