export global SettingsState {
    callback settings-init;
    callback settings-exited;

    in-out property <string> settings-debug-gh-version: "";
    in-out property <string> settings-debug-rate-limit: "";
    in-out property <string> settings-debug-reset-at: "";
    in-out property <string> settings-debug-countdown: "";
    in-out property <string> settings-debug-app-version: "";
    in-out property <string> settings-debug-commit-label: "";
    in-out property <string> settings-debug-error: "";
}
