export component Button {
    height: 32px;
    width: label.preferred-width + (2 * 16px);

    in property label <=> label.text;
    callback clicked <=> ta.clicked;

    Rectangle {
        width: parent.width;
        height: parent.height;
        background: ta.has-hover ? #262c36 : #202830;
        border-radius: 6px;
        border-width: 1px;
        border-color: #3e444d;

        label := Text {
            color: #f0f6fd;
            font-size: 14px;
            font-weight: 600;
        }
    }

    ta := TouchArea { }
}
