import { Palette } from "std-widgets.slint";
import { Avatar, IconButton, Icons, PageHeader } from "../Primer/primer.slint";
import { UserMenu } from "./UserMenu.slint";
import { AppState, Authed, AppView } from "../../bridges/slint/app-state.slint";
import {
    TimeReportingState,
} from "../../bridges/slint/time-reporting-state.slint";
import { Button } from "../Primer/Buttons/buttons.slint";
import { ButtonVariant } from "../Primer/Buttons/types.slint";
import { PrimerColors } from "../Primer/tokens.slint";

global HeaderState {
    in-out property <bool> menu-visible: false;
}

export component AppHeader {

    property <length> title-left-inset: 16px;
    out property <length> header-height: ph.height;

    width: 100%;
    height: 100%;

    ph := PageHeader {
        y: 0;

        HorizontalLayout {
            x: root.title-left-inset;
            y: (parent.height - self.height) / 2;
            height: self.preferred-height;
            width: self.preferred-width;
            spacing: 16px;
            visible: AppState.auth == Authed.loggedIn && (AppState.view == AppView.dashboard || AppState.view == AppView.settings || AppState.view == AppView.timeReporting || AppState.view == AppView.projectBoardList);

            Text {
                text: AppState.view == AppView.dashboard ? "Dashboard" : AppState.view == AppView.settings ? "Settings" : AppState.view == AppView.timeReporting ? "Time reporting" : AppState.view == AppView.projectBoardList ? "Project board" : "";
                font-size: 14px;
                font-weight: 500;
                color: PrimerColors.fgColor-default;
                overflow: elide;
            }
        }

        Button {
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
            visible: AppState.view == AppView.timeReporting && TimeReportingState.has-selected-project;
            label: "Change project";
            variant: ButtonVariant.primary;
            clicked => {
                TimeReportingState.time-reporting-open-change-project();
            }
        }

        sign-in := Button {
            x: parent.width - self.width - self.y;
            y: (parent.height - self.height) / 2;
            visible: AppState.auth == Authed.loggedOut;
            label: "Sign in";
            clicked => {
                AppState.sign_in();
            }
        }

        HorizontalLayout {
            x: parent.width - self.width - self.y;
            y: (parent.height - self.height) / 2;
            visible: AppState.auth == Authed.loggedIn;

            spacing: 8px;
            width: self.preferred-width;
            height: self.preferred-height;

            IconButton {
                y: (parent.height - self.height) / 2;
                clicked => {
                    if (Palette.color-scheme == ColorScheme.dark) {
                        Palette.color-scheme = ColorScheme.light;
                    } else {
                        Palette.color-scheme = ColorScheme.dark;
                    }
                }
                icon-source: Palette.color-scheme == ColorScheme.dark ? Icons.moon : Icons.sun;
            }

            avatar-container := Avatar {
                source: AppState.avatar;
                TouchArea {
                    clicked => {
                        HeaderState.menu-visible = true;
                    }
                }
            }
        }
    }

    TouchArea {
        y: 0;
        width: root.width;
        height: root.height;
        visible: HeaderState.menu-visible;
        clicked => {
            HeaderState.menu-visible = false;
        }
    }

    menu := UserMenu {
        x: parent.width - self.width - 14px;
        y: avatar-container.absolute-position.y + avatar-container.height + 2px;
        avatar-source: AppState.avatar;
        visible: HeaderState.menu-visible;
        user_status_message: AppState.user_status_message;
        user_status_emoji: AppState.user_status_emoji;
    }
}
