import { Button, Spinner } from "../../../../packages/primer-slint/primer.slint";

export component DeviceFlowAuthWindow inherits PopupWindow {
    in property <string> auth-device-code: "";
    callback open-github-device-clicked;

    x: 0;
    y: 0;

    close-policy: no-auto-close;

    Rectangle {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        background: black.with-alpha(0.9);

        TouchArea {
            width: 100%;
            height: 100%;
        }

        VerticalLayout {
            alignment: center;
            spacing: 16px;
            width: self.preferred-width;
            height: 100%;

            Text {
                text: "Finish in the terminal (browser or device flow)";
                font-size: 16px;
                horizontal-alignment: center;
                wrap: word-wrap;
            }

            Text {
                visible: root.auth-device-code != "";
                text: "Your code: ";
                font-size: 18px;
                horizontal-alignment: center;
                wrap: word-wrap;
            }

            TextInput {
                visible: root.auth-device-code != "";
                text: root.auth-device-code;
                font-size: 22px;
                font-weight: 700;
                horizontal-alignment: center;
                wrap: word-wrap;
                read-only: true;
                changed has-focus => {
                    if (self.has-focus) {
                        self.select-all();
                    }
                }
            }

            Button {
                visible: root.auth-device-code != "";
                label: "Copy code to clipboard and open web login";
                clicked => {
                    root.open-github-device-clicked();
                }
            }

            Spinner {
                size: medium;
            }
        }
    }
}
