import { Button } from "../../../../packages/primer-slint/primer.slint";
import { PrimerColors } from "../../../../packages/primer-slint/tokens.slint";

export component GhCliVersionTooOldWindow inherits PopupWindow {
    in property <string> gh-cli-version-block-detail: "";
    callback open_cli_install_page;

    Rectangle {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        background: black;
    }

    VerticalLayout {
        x: (parent.width - self.preferred-width) / 2;
        y: (parent.height - self.preferred-height) / 2;
        width: self.preferred-width;
        height: self.preferred-height;
        spacing: 16px;
        Text {
            text: "GitHub CLI must be updated to at least version 2.89.0";
            font-size: 18px;
            horizontal-alignment: center;
            wrap: word-wrap;
        }

        Text {
            visible: root.gh-cli-version-block-detail != "";
            text: root.gh-cli-version-block-detail;
            font-size: 14px;
            horizontal-alignment: center;
            color: PrimerColors.fgColor-muted;
            wrap: word-wrap;
        }

        Button {
            label: "Open GitHub CLI install page";
            clicked => {
                root.open_cli_install_page();
            }
        }
    }

    close-policy: no-auto-close;
}
