import { Button } from "../../../../packages/primer-slint/primer.slint";

export component NoGhCliInstalledWindow inherits PopupWindow {
    callback open_cli_install_page;

    Rectangle {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        background: black;
    }

    VerticalLayout {
        x: (parent.width - self.preferred-width) / 2;
        y: (parent.height - self.preferred-height) / 2;
        width: self.preferred-width;
        height: self.preferred-height;
        spacing: 20px;
        Text {
            text: "GitHub CLI is not installed";
            font-size: 18px;
            horizontal-alignment: center;
            wrap: word-wrap;
        }

        Button {
            label: "Open CLI install page";
            clicked => {
                root.open_cli_install_page();
            }
        }
    }

    close-policy: no-auto-close;
}
