import { AppState, AppView, Authed } from "../../bridges/slint/app-state.slint";
import { Icons } from "../../../../packages/primer-slint/primer.slint";
import { PrimerColors } from "../../../../packages/primer-slint/tokens.slint";

export component SideBar {
    width: 24px + (16px * 2);
    height: 100%;
    Rectangle {
        height: root.height;
        background: PrimerColors.bgColor-inset;

        Rectangle {
            x: parent.width - self.width;
            width: 1px;
            height: 100%;
            background: PrimerColors.borderColor-default;
        }

        Image {
            x: 16px;
            y: 16px;
            width: 24px;
            height: 24px;
            colorize: PrimerColors.fgColor-muted;
            source: Icons.inbox;

            ta := TouchArea {
                clicked => {
                    AppState.set-view(AppView.dashboard);
                }
            }
        }

        Image {
            x: 16px;
            y: 56px;
            width: 24px;
            height: 24px;
            colorize: PrimerColors.fgColor-muted;
            source: Icons.history;

            TouchArea {
                clicked => {
                    AppState.set-view(AppView.timeReporting);
                }
            }
        }

        Image {
            x: 16px;
            y: 96px;
            width: 24px;
            height: 24px;
            colorize: PrimerColors.fgColor-muted;
            source: Icons.layout_grid;

            TouchArea {
                clicked => {
                    AppState.set-view(AppView.projectBoardList);
                }
            }
        }

        Image {
            x: 16px;
            y: parent.height - self.height - 16px;
            width: 24px;
            height: 24px;
            colorize: PrimerColors.fgColor-muted;
            source: Icons.gear_24;

            TouchArea {
                clicked => {
                    AppState.set-view(AppView.settings);
                }
            }
        }
    }
}