import {
    ActionListItemDivider,
    ActionListRow,
    Avatar,
    Icons,
    MultiDropShadow,
} from "../../../../packages/primer-slint/primer.slint";
import { LayoutTokens, PrimerColors } from "../../../../packages/primer-slint/tokens.slint";
import { AppState } from "../../bridges/slint/app-state.slint";
import { ShadowTokens } from "../../../../packages/primer-slint/tokens.slint";
import { HeaderState } from "./header-state.slint";

global MenuStyle {
    out property <length> border-radius: 12px;
    out property <length> menu-width: 256px;
}

export component UserMenu {

    in-out property <image> avatar-source <=> avatar.source;
    in property <string> user_status_emoji;
    in property <string> user_status_message;

    width: MenuStyle.menu-width;
    height: content.preferred-height;

    // Block clicks
    TouchArea { }

    MultiDropShadow {
        border-radius: MenuStyle.border-radius;
        shadows: ShadowTokens.shadow-floating-small;
    }

    Rectangle {
        border-radius: MenuStyle.border-radius;
        border-width: 1px;
        border-color: PrimerColors.borderColor-default;
        background: PrimerColors.bgColor-inset;
    }

    content := VerticalLayout {
        width: 100%;
        padding: 8px;
        spacing: 8px;

        VerticalLayout {
            padding: 8px;
            spacing: 8px;
            width: parent.width;
            HorizontalLayout {
                spacing: 8px;
                width: self.preferred-width;

                avatar := Avatar { }

                VerticalLayout {
                    height: self.preferred-height;
                    spacing: -3px;
                    Text {
                        width: 120px;
                        text: AppState.user_login;
                        visible: AppState.user_login != "";
                        font-size: LayoutTokens.text-body-size-medium;
                        font-weight: LayoutTokens.base-text-weight-semibold;
                        color: PrimerColors.fgColor-default;
                        overflow: elide;
                    }

                    Text {
                        width: 120px;
                        text: AppState.user_name;
                        visible: AppState.user_name != "";
                        font-size: LayoutTokens.text-body-size-medium;
                        color: PrimerColors.fgColor-muted;
                        font-weight: LayoutTokens.base-text-weight-normal;
                        overflow: elide;
                    }
                }
            }
        }

        ActionListItemDivider {
            width: 100%;
        }

        ActionListRow {
            width: parent.width - (parent.padding * 2);
            label-markdown: @markdown("");
            has-markdown: false;
            label:
                root.user_status_emoji
                + (root.user_status_emoji != "" && root.user_status_message != "" ? " " : "")
                + root.user_status_message;
            clicked => {
            }
        }

        ActionListRow {
            width: parent.width - (parent.padding * 2);
            label-markdown: @markdown("");
            has-markdown: false;
            has-leading-visual: true;
            leading-icon: Icons.sign_out;
            label: "Sign out";
            clicked => {
                HeaderState.menu-visible = false;
                AppState.sign-out();
            }
        }
    }
}
