import { Palette } from "std-widgets.slint";
import { Tokens } from "../tokens.slint";

export component Avatar {

    in-out property source <=> avatar.source;

    width: 34px;
    height: self.width;

    Rectangle {
        width: parent.width - 2px;
        height: self.width;
        border-radius: self.width / 2;
        clip: true;
        avatar := Image {
            width: parent.width;
            height: self.width;
        }
    }

    Rectangle {
        border-width: 1px;
        border-color: Palette.color-scheme == ColorScheme.dark ? #28292d : #D7D8DB;
        border-radius: self.width / 2;
    }

    @children
}