// This file conveniently exports all the components from the Primer Design System.

import { Avatar } from "./Avatar/avatar.slint";
import { IconButton } from "./Buttons/buttons.slint";
import { Select, SelectOption, ValidationStatus } from "./Select/select.slint";
import { Spinner } from "./Progress/spinner.slint";
import { PageHeader } from "./PageHeader/header.slint";

export { Avatar, IconButton, Select, SelectOption, ValidationStatus, Spinner, PageHeader }