#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "generated");
const outFile = join(outDir, "build-info.ts");

let count = 0;
try {
  count = Number.parseInt(
    execFileSync("git", ["rev-list", "--count", "HEAD"], {
      encoding: "utf8",
      cwd: root,
    }).trim(),
    10,
  );
  if (!Number.isFinite(count) || count < 0) {
    count = 0;
  }
} catch {
  count = 0;
}

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  `/** Generated by scripts/write-build-info.ts — do not edit. */
export const GIT_COMMIT_COUNT = ${String(count)} as const;
`,
  "utf8",
);
