// Slint component to simulate CSS style multiple drop-shadows.
export struct DropShadowLayer {
    color: color,
    offset-x: length,
    offset-y: length,
    blur: length,
}

export component MultiDropShadow {
    in property <length> border-radius;
    in property <[DropShadowLayer]> shadows;

    width: 100%;
    height: 100%;

    for shadow in shadows: Rectangle {
        width: 100%;
        height: 100%;
        drop-shadow-color: shadow.color;
        border-radius: border-radius;
        drop-shadow-offset-x: shadow.offset-x;
        drop-shadow-offset-y: shadow.offset-y;
        drop-shadow-blur: shadow.blur;
    }
}
