import { AppState } from "app-state.slint";

global HeaderStyle {
    out property <length> border-radius: 12px;
    out property <color> header-background: #020408;
}

component Avatar {

    in-out property source <=> avatar.source;

    width: 34px;
    height: self.width;

    Rectangle {
        width: parent.width - 2px;
        height: self.width;
        border-radius: self.width / 2;
        clip: true;
        avatar := Image {
            width: parent.width;
            height: self.width;
        }
    }

    Rectangle {
        border-width: 1px;
        border-color: #28292d;
        border-radius: self.width / 2;
    }

    @children
}

component Menu {

    in-out property <image> avatar-source <=> avatar.source;

    width: 256px;
    height: 400px;

    Rectangle {
        border-radius: HeaderStyle.border-radius;
        drop-shadow-offset-y: 6px;
        drop-shadow-blur: 18px;
        drop-shadow-color: #01040966;
    }

    Rectangle {
        border-radius: HeaderStyle.border-radius;
        drop-shadow-offset-y: 6px;
        drop-shadow-blur: 12px;
        drop-shadow-color: #01040966;
    }

    Rectangle {
        border-radius: HeaderStyle.border-radius;
        border-width: 1px;
        border-color: #3e444d;
        background: HeaderStyle.header-background;
    }

    content := Rectangle {

        Rectangle {
            y: 16px;
            x: 16px;
            width: parent.width - (2 * self.x);
            height: 100px - self.y;

            VerticalLayout {
                spacing: 8px;
                width: parent.width;
                HorizontalLayout {
                    spacing: 8px;
                    width: self.preferred-width;

                    avatar := Avatar { }

                    VerticalLayout {
                        y: 3px;
                        height: self.preferred-height;
                        spacing: 4px;
                        Text {
                            width: 120px;
                            text: AppState.user_login;
                            visible: AppState.user_login != "";
                            font-size: 14px;
                            font-weight: 550;
                            color: #f0f6fc;
                            overflow: elide;
                        }

                        Text {
                            width: 120px;
                            text: AppState.user_name;
                            visible: AppState.user_name != "";
                            font-size: 14px;
                            color: #9198a1;
                            font-weight: 400;
                            overflow: elide;
                            letter-spacing: 0.15px;
                        }
                    }
                }
            }

            HorizontalLayout {
                x: 0px;
                y: parent.height - self.height - 14px;
                spacing: 8px;
                width: self.preferred-width;
                height: self.preferred-height;

                Text {
                    text: AppState.user_status_emoji;
                    visible: AppState.user_status_emoji != "";
                    font-size: 14px;
                }

                Text {
                    text: AppState.user_status_message;
                    visible: AppState.user_status_message != "";
                    font-size: 14px;
                    color: #f0f6fc;
                    font-weight: 400;
                }
            }

            Rectangle {
                y: parent.height - self.height;
                width: content.width - 16px;
                height: 1px;
                background: #2b3139;
            }
        }
    }
}

export component Header {
    width: 100%;
    height: 100px;

    property <bool> menu-visible: false;

    Rectangle {
        background: HeaderStyle.header-background;
    }

    Rectangle {
        y: parent.height - self.height;
        width: 100%;
        height: 1px;
        background: #3e444d;
    }

    avatar-container := Avatar {
        x: parent.width - self.width - 14px;
        y: 15px;
        source: AppState.avatar;
        TouchArea {
            clicked => {
                root.menu-visible = !root.menu-visible;
            }
        }
    }

    menu := Menu {
        x: parent.width - self.width - 14px;
        y: avatar-container.y + avatar-container.height + 2px;
        avatar-source: AppState.avatar;
        visible: root.menu-visible;
    }
}
