#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** Directory containing this package (`app/`), i.e. parent of `scripts/`. */
const appRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

function findGitRoot(startDir: string): string {
  let dir = startDir;
  for (;;) {
    if (existsSync(join(dir, ".git"))) {
      return dir;
    }
    const parent = join(dir, "..");
    if (parent === dir) {
      return startDir;
    }
    dir = parent;
  }
}

const gitRoot = findGitRoot(appRoot);
const outDir = join(appRoot, "generated");
const outFile = join(outDir, "build-info.ts");

let count = 0;
try {
  count = Number.parseInt(
    execFileSync("git", ["rev-list", "--count", "HEAD"], {
      encoding: "utf8",
      cwd: gitRoot,
    }).trim(),
    10,
  );
  if (!Number.isFinite(count) || count < 0) {
    count = 0;
  }
} catch {
  count = 0;
}

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  `/** Generated by scripts/write-build-info.ts — do not edit. */
export const GIT_COMMIT_COUNT = ${String(count)} as const;
`,
  "utf8",
);
